//
// GetTransactionStatusResponseData.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTransactionStatusResponseData: Codable, JSONEncodable, Hashable {

    public var transactionStatus: String?
    public var bankReferenceNumber: String?
    public var npciTxnId: String?

    public init(transactionStatus: String? = nil, bankReferenceNumber: String? = nil, npciTxnId: String? = nil) {
        self.transactionStatus = transactionStatus
        self.bankReferenceNumber = bankReferenceNumber
        self.npciTxnId = npciTxnId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionStatus
        case bankReferenceNumber
        case npciTxnId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(transactionStatus, forKey: .transactionStatus)
        try container.encodeIfPresent(bankReferenceNumber, forKey: .bankReferenceNumber)
        try container.encodeIfPresent(npciTxnId, forKey: .npciTxnId)
    }
}

