//
// GetTransactionStatusResponseError.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetTransactionStatusResponseError: Codable, JSONEncodable, Hashable {

    public var message: String?
    public var responseCode: String?

    public init(message: String? = nil, responseCode: String? = nil) {
        self.message = message
        self.responseCode = responseCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case responseCode = "response_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(responseCode, forKey: .responseCode)
    }
}

