//
// IssueCollectRequestRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IssueCollectRequestRequest: Codable, JSONEncodable, Hashable {

    public var referenceId: String
    public var payerUpi: String
    public var payeeAccount: String
    public var amount: Double
    public var purposeMessage: String
    public var expiryTime: Int?

    public init(referenceId: String, payerUpi: String, payeeAccount: String, amount: Double, purposeMessage: String, expiryTime: Int? = nil) {
        self.referenceId = referenceId
        self.payerUpi = payerUpi
        self.payeeAccount = payeeAccount
        self.amount = amount
        self.purposeMessage = purposeMessage
        self.expiryTime = expiryTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referenceId = "reference_id"
        case payerUpi = "payer_upi"
        case payeeAccount = "payee_account"
        case amount
        case purposeMessage = "purpose_message"
        case expiryTime = "expiry_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(referenceId, forKey: .referenceId)
        try container.encode(payerUpi, forKey: .payerUpi)
        try container.encode(payeeAccount, forKey: .payeeAccount)
        try container.encode(amount, forKey: .amount)
        try container.encode(purposeMessage, forKey: .purposeMessage)
        try container.encodeIfPresent(expiryTime, forKey: .expiryTime)
    }
}

