//
// IssueCollectRequestResponseData.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IssueCollectRequestResponseData: Codable, JSONEncodable, Hashable {

    public var transactionId: String?
    public var transactionStatus: String?
    public var transactionStatusDescription: String?
    public var bankReferenceNumber: String?
    public var npciTransactionId: String?

    public init(transactionId: String? = nil, transactionStatus: String? = nil, transactionStatusDescription: String? = nil, bankReferenceNumber: String? = nil, npciTransactionId: String? = nil) {
        self.transactionId = transactionId
        self.transactionStatus = transactionStatus
        self.transactionStatusDescription = transactionStatusDescription
        self.bankReferenceNumber = bankReferenceNumber
        self.npciTransactionId = npciTransactionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId
        case transactionStatus
        case transactionStatusDescription
        case bankReferenceNumber
        case npciTransactionId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(transactionId, forKey: .transactionId)
        try container.encodeIfPresent(transactionStatus, forKey: .transactionStatus)
        try container.encodeIfPresent(transactionStatusDescription, forKey: .transactionStatusDescription)
        try container.encodeIfPresent(bankReferenceNumber, forKey: .bankReferenceNumber)
        try container.encodeIfPresent(npciTransactionId, forKey: .npciTransactionId)
    }
}

