//
// ValidateUpiHandleRequest.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidateUpiHandleRequest: Codable, JSONEncodable, Hashable {

    public var referenceId: String
    public var upiId: String
    public var type: String?

    public init(referenceId: String, upiId: String, type: String? = nil) {
        self.referenceId = referenceId
        self.upiId = upiId
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case referenceId = "reference_id"
        case upiId = "upi_id"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(referenceId, forKey: .referenceId)
        try container.encode(upiId, forKey: .upiId)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

