//
// ValidateUpiHandleResponseData.swift
//
// Generated by Konfig
// https://konfigthis.com
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ValidateUpiHandleResponseData: Codable, JSONEncodable, Hashable {

    public var upiId: String?
    public var name: String?
    public var status: String?
    public var statusDescription: String?

    public init(upiId: String? = nil, name: String? = nil, status: String? = nil, statusDescription: String? = nil) {
        self.upiId = upiId
        self.name = name
        self.status = status
        self.statusDescription = statusDescription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case upiId
        case name
        case status
        case statusDescription
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(upiId, forKey: .upiId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(statusDescription, forKey: .statusDescription)
    }
}

